# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WorkerName', models.CharField(max_length=25)),
                ('WorkerSecondName', models.CharField(max_length=25)),
                ('WorkerEmail', models.CharField(max_length=25)),
                ('WorkerMobile', models.CharField(max_length=25)),
                ('WorkerPost', models.CharField(max_length=25)),
            ],
        ),
    ]
