# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffworker',
            name='WorkerEmail',
            field=models.CharField(max_length=25, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='staffworker',
            name='WorkerMobile',
            field=models.CharField(max_length=25, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='staffworker',
            name='WorkerName',
            field=models.CharField(max_length=25, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='staffworker',
            name='WorkerPost',
            field=models.CharField(max_length=25, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='staffworker',
            name='WorkerSecondName',
            field=models.CharField(max_length=25, verbose_name='Фамилия'),
        ),
    ]
